### ISSUE TITLE
Rails development mode and newrelic

### ISSUE THREAD

**Issue by chrisdebruin** [sinsoku/rails-env-credentials#1]
I had some strange behaviour using this gem and newrelic gem. I placed `gem 'rails-env-credentials'` below `gem 'newrelic_rpm'` in my Gemfile and use `Rails.application.credentials` in `newrelic.yml` to load the license_key.

When I start my app in development the`credentials.yml.enc` is used instead of `credentials-development.yml.enc`. Since newrelic is loaded in a very early stage it loads the production credentials instead of development credentials.

The only way to fix this was putting the gem **before** newrelic gem in my Gemfile. Not sure if this is a fixable issue but I think it would be good to mention it in the README.

Thanks

**Comment by sinsoku** [comment]
Thanks for the report!
This issue was fixed by https://github.com/sinsoku/rails-env-credentials/pull/2 and released to `v0.1.3`. Try to upgrade.
